### ISSUE TITLE
[AppStore] CategoryID not retrievable. 

### ISSUE THREAD

**Issue by nilbro** [eclipse/kuksa.cloud#105]
Whenever I want to create a new app with an old category, the categoryid is not found. This leads to failure in creating new apps in the appstore remotely (viz Spring/Python requests). 

Is there any way (viz. A SQL interface) that can be used?

**Comment by trademkose** [comment]
I consider this is not a bug.
The categoryid is not retrievable, because of the database's sequence generates id as incrementally  for categories. If you want to edit your category id, you can access to H2 console. You can execute sql script on H2 console to edit your category id.

http://appstoreIP:port/console/

Note : 
If there is no application category on your appstore , you can add it in Profile page-> Application Category tab.
![resim](https://user-images.githubusercontent.com/7984679/63755462-62003400-c8bf-11e9-8d9e-8b971c63e33b.png)
And than you can create a new app with the category that you added.

**Comment by rai20** [comment]
but is it possible to have a REST api for the category ID so that the app publishers could check if the category already exists and what ID it corresponse to?

**Comment by trademkose** [comment]
@rai20 It can be implemented like that we can add a new Rest Api path to search categoryName.
GET - /api/1.0/appcategory/{appCategoryName}

If a category is found with the given category name, it means there is a category like this. If the new Rest Api path returns null it means there is no category.
