### ISSUE TITLE
dns zone for deployment/azure/allocate_static_ip_address_and_dns_names

### ISSUE THREAD

**Issue by soheilade** [eclipse/kuksa.cloud#154]
Dear all, I am trying to run the script for allocating static ip addresses and I get an error regarding the dns zone argument. Do I need to create a zone before running this script using 
```
az network dns zone create --name
                           --resource-group
                           [--if-none-match]
                           [--parent-name]
                           [--registration-vnets]
                           [--resolution-vnets]
                           [--subscription]
                           [--tags]
                           [--zone-type]
```
if so what is the command to create this zone? any optional parameters is required?

**Comment by eriksven** [comment]
Yes, it looks like you need to create that DNS zone manually before executing the script in https://github.com/eclipse/kuksa.cloud/blob/master/deployment/azure/allocate_static_ip_address_and_dns_names.sh
Unfortunately, my knowledge about this script is a bit vague because it was contributed by someone else and I rarely used it. But I would expect that you do not require any of the optional parameters.

**Comment by soheilade** [comment]
thanks @eriksven , It worked without any parameter, just the name must consist of 3 parts (e.g., www.mydns.com).
