### ISSUE TITLE
Kuksa-Appstore still uses DUMMY_SOFTWARE_MODULE after the UNINSTALL_ALL Changes

### ISSUE THREAD

**Issue by rai20** [eclipse/kuksa.cloud#43]
It seems the appstore still uses the DUMMY_SOFTWARE_MODULE in its deployment after it was removed as part of the UNINSTALL_ALL change. I checked out the new version of appstore and tried deploying an app and found that the DUMMY_SOFTWARE_MODULE is deployed along with the actual app artifacts (see image below). I was expecting only the app artifacts to be deployed and not the DUMMY_SOFTWARE_MODULE. 

![kuksa-bug](https://user-images.githubusercontent.com/40228920/54115868-c3a21400-43ed-11e9-935c-959d1d465775.png)

App-manager log running on raspberrypi. The version of app-manager used is latest from github and modified to work with UNINSTALL_ALL change.

![kuksa-bug2](https://user-images.githubusercontent.com/40228920/54115891-d1f03000-43ed-11e9-96c8-319f44415ef4.png)

**Comment by trademkose** [comment]
Hi Rai,
You are working with your old data on your Hawkbit. You need to reset your Hawkbit before you want to use new version of Appstore. Because of the Dummy_software_module's name was changed to UNINSTALLED_ALL, so the new version of Appstore can not remove Dummy_software_module from your distribution.

**Comment by rai20** [comment]
Ok. Got it. But if i a create a new target, there should not be any issue right?

**Comment by eriksven** [comment]
@rai20 can we close this issue?

**Comment by rai20** [comment]
yes. The issue is fixed.
