### ISSUE TITLE
[Appstore] Issue connecting to Hawkbit

### ISSUE THREAD

**Issue by m-lenz** [eclipse/kuksa.cloud#63]
I built the new app-store (amd) with the new HawkBit-Ip and ran it locally.
Despite the correct IP inside the `application.properties`, creating new apps inside the app-store return an `connection error` and prompt me to change the properties IP-address .

**Comment by m-lenz** [comment]
[![hbissue.png](https://i.postimg.cc/JhyKbKkr/hbissue.png)](https://postimg.cc/wtphzX2Z)

**Comment by trademkose** [comment]
Hi,
It seems like your Appstore instance can not acces to your Hawkbit instance.
Which hawkbit version do you use?
I use Hawkbit latest version. I don't get any error.
Could you share your hawkbit version and application.properties file?

**Comment by m-lenz** [comment]
# Config:
as stated [here](https://github.com/eclipse/kuksa.cloud/tree/master/kuksa-appstore) except new `IPs`
[![appman-config.png](https://i.postimg.cc/8cTF2j50/appman-config.png)](https://postimg.cc/Q9nx5NcQ)

> logins blurred but correct

No idea, which version is currently used, I tried to find out, but I cant find it (in case it is stated on HawkBit)

**Comment by trademkose** [comment]
![resim](https://user-images.githubusercontent.com/7984679/57856700-39fc3180-77f6-11e9-9364-d492ed4b16be.png)
There is ";" and space character in your hawkbit hsot variable. I think this charcters may occur your errors. Notice that.

**Comment by m-lenz** [comment]
`;` indicates comments, which should not be an issue, since it is used above in line 3.
There is no space between the parameter an the `;`. It just looks this way due to `rxvt-unicode`.

The only spaces in the config are before / after `=` which shouldn't be a problem either, since it conforms to the `java-coding-conventions`

**Comment by m-lenz** [comment]
[![spaces-in-config.png](https://i.postimg.cc/xdqWKP7y/spaces-in-config.png)](https://postimg.cc/3y5Sh23d)

`ack-grep` highlighting spaces

**Comment by selobosi** [comment]
> 
> 
> `;` indicates comments, which should not be an issue, since it is used above in line 3.
> There is no space between the parameter an the `;`. It just looks this way due to `rxvt-unicode`.
> 
> The only spaces in the config are before / after `=` which shouldn't be a problem either, since it conforms to the `java-coding-conventions`

Could you provide a link "to the `java-coding-conventions`" you are referring to? It's good to mention such things, but it's also nice to make them easily findable for those who don't know them (like me).

Have these conventions been agreed to apply in this project?

**Comment by m-lenz** [comment]
I have no idea, where they are kept for reference. But I am trying to say, that the space is not the issue.
The project uses the annotation " =" and "= " ~1000 times each, I doubt the space inside the config is the issue.

**Comment by m-lenz** [comment]
Tried old and new HawkBit-IPs with and without spaces in the config, but the outcome is still the same

**Comment by selobosi** [comment]
@m-lenz, I'd like to encourage you to question your knowledge to generate further potential solutions: @trademkose suggested in https://github.com/eclipse/kuksa.cloud/issues/63#issuecomment-493065427 that you should remove the `;` from the end of the `hawkbit.host`. You assumed in https://github.com/eclipse/kuksa.cloud/issues/63#issuecomment-493893151 that `;` is a comment character and is correct. Assuming that any one of you could be right, feel free to assume that @trademkose is right and give his suggestion a try and remove the `;` and see if it fixes the problem.

Another way of verifying one's knowledge is to look for authoritative sources of information. That was part of my intention for https://github.com/eclipse/kuksa.cloud/issues/63#issuecomment-494242913: I suggested to look for a reference because file formats may be different than expected: The reference helps here, too: [the JavaDoc of the Java class that reads property files](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader- ) says that comments are lines starting with either `#` or `!`. So that's another hint at why it might be useful to try to remove the `;`.

Let us know if that fixes the issue!

**Comment by m-lenz** [comment]
I does not.

**Comment by m-lenz** [comment]
@selobosi 
[the JavaDoc of the Java class that reads property files](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader-) states that 
> Any white space after the key is skipped; if the first non-white space character after the key is '=' or ':', then it is ignored and any white space characters after it are also skipped

I was talking about the spaces inside the config-file, not the `;`. That's why it's separated into 2 paragraphs.

**Comment by selobosi** [comment]
Ok, hm, so just to verify I have the correct idea of the most minimal configuration that still produces the error:
* you are starting hawkbit locally (not in Docker)
* in the properties file you have configured `hawkbit.host=http://hawkbit-appstacle.westeurope.cloudapp.azure.com` and `hawkbit.port=8080` - i.e. without spaces, semicolons, whatever

When typing this it appears to me that hawkbit.host could only be a hostname, i.e. without `http://`. Does that work?

(I assume that you are able to connect to http://hawkbit-appstacle.westeurope.cloudapp.azure.com:8080/ from a browser or `curl` running in the same VM / operating system in which you start the appstore.)

**Comment by m-lenz** [comment]
> When typing this it appears to me that hawkbit.host could only be a hostname, i.e. without http://. Does that work?

Yes! We had to add the protocol in to resolve the new URL to IP, but apparently now it is rather harmful

**Comment by selobosi** [comment]
Ok, great!

Would you like to submit a pull request for the code that permits configuration of URLs (e.g. in a property called hawkbit.url) instead of hawkbit.hostname and hawkbit.port or shall someone else implement that?

**Comment by m-lenz** [comment]
I am not qualified enough to determine, if concatenating the `hostname` and `port` would bring improvements to the code or add more work (e.g. splitting string up again) or possible errors (some subroutine still uses old config)

If this adaption is useful I can change the code to conform to the new config and submit a new PR.

**Comment by m-lenz** [comment]
I am not qualified enough to determine, if concatenating the `hostname` and `port` would bring improvements to the code or add more work (e.g. splitting string up again) or possible errors (some subroutine still uses old config)

If this adaption is useful I can change the code to conform to the new config and submit a new PR.

**Comment by selobosi** [comment]
Oh, sorry, when reading https://github.com/eclipse/kuksa.cloud/issues/63#issuecomment-494413636 I had the false impression that you had already implemented that change. My mistake! Most likely you meant that you/@alezor are already using HTTPS URLs in the integration tests. So I'll create a new issue for configuring URLs instead of hostname and port for @trademkose.

Please feel free to close this issue if you consider it resolved.
